# Generated by Django 4.2 on 2026-03-18 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='in_progress',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='overdue',
            field=models.BooleanField(default=False),
        ),
    ]
