# Generated by Django 4.2 on 2026-03-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0007_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'managed': True, 'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
