# Generated by Django 6.0.3 on 2026-03-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0010_alter_emailverificationtoken_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_members',
            field=models.TextField(blank=True, help_text='Comma-separated member IDs'),
        ),
    ]
